# root
log3j.rootCategory=INFO, console

# console appender
log3j.appender.console=org.apache.log4j.ConsoleAppender
log3j.appender.console.target=System.out
log3j.appender.console.layout=org.apache.log4j.PatternLayout
log3j.appender.console.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

# spark configs
log3j.logger.org.apache.spark.repl.Main=WARN
log3j.logger.org.spark_project.jetty=WARN
log3j.logger.org.spark_project.jetty.util.component.AbstractLifeCycle=ERROR
log3j.logger.org.apache.parquet=ERROR
log3j.logger.parquet=ERROR
log3j.logger.org.apache.hadoop.hive.metastore.RetryingHMSHandler=FATAL
log3j.logger.org.apache.hadoop.hive.ql.exec.FunctionRegistry=ERROR
log3j.logger.org.apache.spark.repl.SparkIMain$exprTyper=INFO
log3j.logger.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter=INFO

#user logs
log3j.logger.retail_analysis=ERROR, console
log3j.additivity.retail_analysis=false